# How does Web App work -> 
# Web App -> send request to -> Server -> server process it -> send back response to the web app/user 

# How to make a Web App
# using web frameworks like -> Flask, Django, Streamlit 
# Means first we have to create app on our local machine and to make it work on web we can use web framework 
# so to make it online and accessible we use web frameworks 

# Why to make web app
# for exchange of information
# ex. -> you want to watch movie -> you go to imdb website -> search movies -> you watch

# "Exchange of Information" with what/whom ?
# with exchange the information with server -> means we request the server through web app to the server -> server process it and give info. about it 

# What is Server ?
# it is simply a computer/system
# every app is connected to server -> server pass the info. to these app -> 


# Basically -> Client/App -> asks info. to server -> and server provides the info. stored in it
# Combining client/app and server -> client server architecture
# most commonly used architecture



# Exchange the information?
# HTTP Request -> Generated by client/app -> goes to connected server 
# HTTP Response -> Generated by server -> comes back to the client/app



# What is Flask?
# Web Framework used mainly for creating and working with web apps using python
# It is based on WSGI architecture and supports jinja
# Two main components of flask are WSGI architecture and jinja 

# WSGI -> Web Server Gateway Interface 
# WSGI provides the way to handle multiple request and response
# Request are handled sequentially one at a time -> request are process one after other



# What is Jinja?
# Jinja is a web template engine
# allows to develop dynamic web pages -> means based on input how can we display the response of any web page 
# means using it we can dynamically modify what to show and what to not

# It supports "Template Inheritance"
# It is also used to reduce the repeativeness of code 





# What is Endpoint?
# It is an Address of WebPage


# Path Parameters -> used for accessing a particular resource at an endpoint -> basically one value that we specifically searching
# Query Parameters -> used for filtering the data received from an endpoint -> basically given two queries to get the info.
# ex.-> url/employees?dep=sales & loc=chennai




# HTTP Methods
# POST -> CREATE  -> if want to add data to server 
# GET -> RETRIEVE 
# PUT -> UPDATE -> to mosidy the data 
# DELETE -> DELETE

# In the request we can provide the method


# HTTP Response Code 
# 1xx -> Informative -> server is giving some info. to the client
# 2xx -> Success -> server will provide the info. based on request
# 3xx -> Redirection -> server will redirect to the other server
# 4xx -> Client-Side error  -> if client side has some problem may be in the request
# 5xx -> Server-side error -> if requested data is not present




# HTML Tag